import {alertRoutes} from './alerts.mjs';
import {uid,eventIdentity,safeUrl,validateProject,exhibitionTasks,TASK_STATUS} from './model.mjs';

const enc=new TextEncoder();
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
const sha=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',typeof s==='string'?enc.encode(s):s))).map(x=>x.toString(16).padStart(2,'0')).join('');
async function passwordHash(password,salt){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);return Array.from(new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:enc.encode(salt),iterations:100000},key,256))).map(x=>x.toString(16).padStart(2,'0')).join('');}
async function body(req,max=6_000_000){const raw=await req.text();if(raw.length>max)throw Error('This request is too large.');try{return JSON.parse(raw);}catch{throw Error('The saved data could not be read.');}}
const audit=(db,user,type,id,action,detail={})=>db.prepare('INSERT INTO activity(id,entity_type,entity_id,action,user_id,detail) VALUES(?,?,?,?,?,?)').bind(uid(),type,id,action,user.id,JSON.stringify(detail));
const query=async(db,sql,...args)=>(await db.prepare(sql).bind(...args).all()).results;
const one=(db,sql,...args)=>db.prepare(sql).bind(...args).first();
const payloads=rows=>rows.map(r=>JSON.parse(r.payload));
function secure(response){const h=new Headers(response.headers);h.set('x-content-type-options','nosniff');h.set('referrer-policy','strict-origin-when-cross-origin');h.set('x-frame-options','SAMEORIGIN');h.set('permissions-policy','camera=(), microphone=(), geolocation=()');return new Response(response.body,{status:response.status,headers:h});}

async function fetchHandler(req,env){
 const u=new URL(req.url),p=u.pathname,db=env.DB,now=Math.floor(Date.now()/1000);
 if(p==='/api/health')return json({ok:true,service:'Pisell Global Growth'});
 const token=req.headers.get('cookie')?.match(/(?:^|;\s*)pisell_session=([^;]+)/)?.[1];
 const user=token?await one(db,'SELECT users.id,users.name,users.email,users.role FROM sessions JOIN users ON users.id=sessions.user_id WHERE token_hash=? AND expires_at>?',await sha(token),now):null;
 const mutation=!['GET','HEAD','OPTIONS'].includes(req.method);
 if(mutation&&req.headers.get('origin')!==u.origin)return json({error:'Please save from the workspace page.'},403);
 if(p==='/api/login'&&req.method==='POST'){
  const input=await body(req,4000),ip=req.headers.get('cf-connecting-ip')||'local',key=await sha(ip),limit=await one(db,'SELECT * FROM login_attempts WHERE key=?',key);
  if(limit&&limit.reset_at>now&&limit.attempts>=10)return json({error:'Too many attempts. Please try again in 15 minutes.'},429);
  const account=typeof input.email==='string'?await one(db,'SELECT * FROM users WHERE lower(email)=?',input.email.trim().toLowerCase()):null;
  const hash=await passwordHash(String(input.password||''),account?.password_salt||'unavailable');
  if(!account||hash!==account.password_hash){await db.prepare('INSERT INTO login_attempts(key,attempts,reset_at) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET attempts=CASE WHEN reset_at<=? THEN 1 ELSE attempts+1 END,reset_at=CASE WHEN reset_at<=? THEN excluded.reset_at ELSE reset_at END').bind(key,now+900,now,now).run();return json({error:'Email or password is incorrect.'},401);}
  const session=uid()+uid(),expiry=now+43200;
  await db.batch([db.prepare('INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)').bind(await sha(session),account.id,expiry),db.prepare('DELETE FROM login_attempts WHERE key=?').bind(key),db.prepare('DELETE FROM sessions WHERE expires_at<=?').bind(now)]);
  return json({ok:true},200,{'set-cookie':`pisell_session=${session}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=43200`});
 }
 if(p==='/api/session')return json(user?{...user,signedIn:true,canEdit:user.role!=='viewer'}:{signedIn:false,canEdit:false});
 if(p==='/api/logout'&&req.method==='POST'){if(token)await db.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha(token)).run();return json({ok:true},200,{'set-cookie':'pisell_session=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0'});}
 if(!user){if(p.startsWith('/api/')||p==='/data.json')return json({error:'Please sign in to continue.'},401);if(!['/','/index.html','/app.js','/config.js','/style.css','/navigation.css','/alerts.css','/trigger-settings.css','/detail-interactions.js','/pisell-logo.png','/favicon.ico'].includes(p))return new Response('Sign in required',{status:401});return env.ASSETS.fetch(req);}
 if(mutation&&user.role==='viewer')return json({error:'Editing access is required.'},403);
 const alertResponse=await alertRoutes(req,env,user);if(alertResponse)return alertResponse;
 if(p==='/api/bootstrap'){
  const [projects,users,regions,activity,counts]=await Promise.all([
   query(db,`SELECT p.*,u.name owner_name,(SELECT count(*) FROM tasks t WHERE t.project_id=p.id AND t.status!='cancelled') task_count,(SELECT count(*) FROM tasks t WHERE t.project_id=p.id AND t.status='done') done_count,(SELECT count(*) FROM tasks t WHERE t.project_id=p.id AND t.needs_decision=1 AND t.status NOT IN ('done','cancelled')) decision_count FROM work_projects p LEFT JOIN users u ON u.id=p.owner_id ORDER BY p.updated_at DESC`),
   query(db,'SELECT id,name FROM users'),query(db,'SELECT * FROM regions'),query(db,'SELECT a.*,u.name user_name FROM activity a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 15'),
   one(db,`SELECT (SELECT count(*) FROM exhibitions) exhibitions,(SELECT count(*) FROM venues v WHERE v.id IN (SELECT venue_id FROM venue_collections WHERE collection='melbourne') AND NOT EXISTS(SELECT 1 FROM exclusions e WHERE e.id=v.id) AND NOT EXISTS(SELECT 1 FROM venue_identity_keys vk JOIN exclusion_keys ek ON ek.key=vk.key WHERE vk.venue_id=v.id)) venues,(SELECT count(DISTINCT company_id) FROM partners WHERE status='active') partners,(SELECT count(*) FROM opportunities WHERE disposition='active') opportunities,(SELECT count(DISTINCT o.company_id) FROM opportunities o JOIN milestone_confirmations m ON m.opportunity_id=o.id WHERE m.milestone='V3' AND m.revoked_at IS NULL) customers`)
  ]);return json({user,projects,users,regions,activity,counts});
 }
 if(p==='/api/projects'&&req.method==='POST'){
  const input=validateProject(await body(req,25000)),id=uid();
  if(input.exhibition_id){const existing=await one(db,'SELECT id FROM work_projects WHERE exhibition_id=?',input.exhibition_id);if(existing)return json({id:existing.id,existing:true});if(!await one(db,'SELECT id FROM exhibitions WHERE id=?',input.exhibition_id))throw Error('The exhibition could not be found.');}
  const level=input.exhibition_id?Number(input.exhibition_level||1):null;
  const statements=[db.prepare('INSERT INTO work_projects(id,name,workstream,work_type,status,owner_id,country,due_date,next_action,deliverable,exhibition_level,exhibition_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,input.name.trim(),input.workstream,input.work_type||'general',input.status||'draft',input.owner_id||null,input.country||null,input.due_date||null,input.next_action||null,input.deliverable||null,level,input.exhibition_id||null),audit(db,user,'project',id,'Project created',{name:input.name})];
  if(level)statements.push(...exhibitionTasks(level).map(title=>db.prepare('INSERT INTO tasks(id,project_id,title,owner_id) VALUES(?,?,?,?)').bind(uid(),id,title,input.owner_id||null)));
  await db.batch(statements);return json({id},201);
 }
 const project=p.match(/^\/api\/projects\/([^/]+)$/);
 if(project){const id=decodeURIComponent(project[1]);const record=await one(db,'SELECT * FROM work_projects WHERE id=?',id);if(!record)return json({error:'Project not found.'},404);
  if(req.method==='GET'){const [tasks,activity,files]=await Promise.all([query(db,'SELECT * FROM tasks WHERE project_id=? ORDER BY rowid',id),query(db,'SELECT a.*,u.name user_name FROM activity a LEFT JOIN users u ON u.id=a.user_id WHERE entity_type=? AND entity_id=? ORDER BY created_at DESC','project',id),query(db,'SELECT * FROM files WHERE project_id=? ORDER BY created_at DESC',id)]);return json({...record,tasks,activity,files});}
  if(req.method==='PATCH'){const input=validateProject({...record,...await body(req,25000)});if(input.revision!==record.revision)return json({error:'This project changed elsewhere. Reopen it to review the latest version.'},409);
   const result=await db.prepare('UPDATE work_projects SET name=?,workstream=?,status=?,owner_id=?,country=?,due_date=?,next_action=?,deliverable=?,outcome=?,revision=revision+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND revision=?').bind(input.name.trim(),input.workstream,input.status,input.owner_id||null,input.country||null,input.due_date||null,input.next_action||null,input.deliverable||null,input.outcome||null,id,input.revision).run();if(!result.meta.changes)return json({error:'This project changed elsewhere. Reload before saving.'},409);await audit(db,user,'project',id,'Project updated').run();return json({ok:true});}
 }
 if(p==='/api/tasks'&&req.method==='POST'){const input=await body(req,10000);if(typeof input.title!=='string'||!input.title.trim()||input.title.length>500)throw Error('Enter a task title, up to 500 characters.');if(!await one(db,'SELECT id FROM work_projects WHERE id=?',input.project_id))throw Error('Project not found.');const id=uid();await db.batch([db.prepare('INSERT INTO tasks(id,project_id,title,owner_id,due_date,needs_decision) VALUES(?,?,?,?,?,?)').bind(id,input.project_id,input.title.trim(),input.owner_id||null,input.due_date||null,input.needs_decision?1:0),audit(db,user,'project',input.project_id,'Task added',{title:input.title})]);return json({id},201);}
 const task=p.match(/^\/api\/tasks\/([^/]+)$/);
 if(task&&req.method==='PATCH'){const input=await body(req,10000),record=await one(db,'SELECT * FROM tasks WHERE id=?',task[1]);if(!record)return json({error:'Task not found.'},404);if(!TASK_STATUS.includes(input.status))throw Error('Choose a valid task status.');const result=await db.prepare('UPDATE tasks SET status=?,revision=revision+1 WHERE id=? AND revision=?').bind(input.status,task[1],input.revision).run();if(!result.meta.changes)return json({error:'This task changed elsewhere. Reload the project.'},409);await audit(db,user,'project',record.project_id,'Task updated',{title:record.title,status:input.status}).run();return json({ok:true});}
 if(p==='/api/exhibitions'){
  const [meta,events,sources,notes]=await Promise.all([one(db,'SELECT payload FROM dataset_metadata WHERE key=?','exhibitions'),query(db,'SELECT payload FROM exhibitions ORDER BY start_date,name'),query(db,"SELECT s.payload FROM sources s JOIN source_collections sc ON sc.source_id=s.id WHERE sc.collection='exhibitions'"),query(db,"SELECT * FROM record_notes WHERE entity_type='exhibition'")]);
  return json({...JSON.parse(meta?.payload||'{}'),events:payloads(events),sources:payloads(sources),notes:Object.fromEntries(notes.map(n=>[n.entity_id,{text:n.text,review:n.review,updatedAt:n.updated_at,revision:n.revision}]))});
 }
 if(p==='/api/exhibitions/save'&&req.method==='POST'){
  const input=await body(req),events=input.events||[],sources=input.sources||[],notes=input.notes||{},statements=[];if(!Array.isArray(events)||!Array.isArray(sources)||events.length>500||sources.length>2000)throw Error('Import up to 500 opportunities at a time.');
  const known=await query(db,'SELECT id,url FROM sources');const sourceMap=new Map(known.map(s=>[s.id,s.url]));const urlMap=new Map(known.map(s=>[s.url,s.id]));
  for(const s of sources){if(typeof s.id!=='string'||!safeUrl(s.url))throw Error('Every source needs a valid id and website.');if(sourceMap.has(s.id)&&sourceMap.get(s.id)!==s.url)throw Error('A source id is already linked to another website.');if(urlMap.has(s.url)&&urlMap.get(s.url)!==s.id)throw Error('This website already has a source id. Keep its existing id.');sourceMap.set(s.id,s.url);urlMap.set(s.url,s.id);statements.push(db.prepare('INSERT INTO sources(id,url,publisher,payload) VALUES(?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(s.id,s.url,s.name||s.publisher||'',JSON.stringify(s)));statements.push(db.prepare("INSERT INTO source_collections(collection,source_id) VALUES('exhibitions',?) ON CONFLICT DO NOTHING").bind(s.id));}
  const existingEvents=await query(db,'SELECT id,identity_key FROM exhibitions');const existingIds=new Set(existingEvents.map(e=>e.id));const existingIdentities=new Set(existingEvents.map(e=>e.identity_key));
  let added=0;
  for(const e of events){if(!e.id||!e.name||!e.country||!/^\d{4}-\d{2}-\d{2}$/.test(e.start)||!/^\d{4}-\d{2}-\d{2}$/.test(e.end)||e.end<e.start)throw Error('Every exhibition needs a name, country and valid date range.');if(existingIds.has(e.id)||existingIdentities.has(eventIdentity(e)))continue;if(!e.sourceIds?.length||e.sourceIds.some(id=>!sourceMap.has(id)))throw Error('Every opportunity must cite known sources.');const payload={...e,evidence:'Unverified',confidence:'unverified'};statements.push(db.prepare('INSERT INTO exhibitions(id,identity_key,name,country,city,venue,start_date,end_date,confidence,payload) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(e.id,eventIdentity(e),e.name,e.country,e.city||null,e.venue||null,e.start,e.end,'unverified',JSON.stringify(payload)));statements.push(...e.sourceIds.map(s=>db.prepare('INSERT INTO exhibition_sources(exhibition_id,source_id) VALUES(?,?)').bind(e.id,s)));existingIds.add(e.id);existingIdentities.add(eventIdentity(e));added++;}
  for(const [id,n]of Object.entries(notes)){if(!existingIds.has(id)||typeof n.text!=='string'||n.text.length>10000||!['Not reviewed','Shortlisted','Needs follow-up','Not a priority'].includes(n.review))throw Error('Check the note and review status.');const current=await one(db,"SELECT * FROM record_notes WHERE entity_type='exhibition' AND entity_id=?",id);if(current&&current.text===n.text&&current.review===n.review)continue;if(current&&(n.revision??0)!==current.revision)return json({error:'A note changed in another session. Export your changes, then reload before saving.'},409);if(current)statements.push(db.prepare("UPDATE record_notes SET text=?,review=?,revision=CASE WHEN revision=? THEN revision+1 ELSE NULL END,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE entity_type='exhibition' AND entity_id=?").bind(n.text,n.review,current.revision,user.id,id));else statements.push(db.prepare("INSERT INTO record_notes(entity_type,entity_id,text,review,updated_by) VALUES('exhibition',?,?,?,?)").bind(id,n.text,n.review,user.id));}
  if(statements.length)await db.batch([...statements,audit(db,user,'exhibition','collection','Research saved',{added,notes:Object.keys(notes).length})]);return json({ok:true,added});
 }
 if(p==='/api/data'||p==='/data.json'||p==='/api/venues'){
  const [meta,rows]=await Promise.all([one(db,'SELECT payload FROM dataset_metadata WHERE key=?','venues'),query(db,"SELECT v.payload FROM venues v WHERE (v.id IN (SELECT venue_id FROM venue_collections WHERE collection='melbourne') OR ?='all') AND NOT EXISTS(SELECT 1 FROM exclusions e WHERE e.id=v.id) AND NOT EXISTS(SELECT 1 FROM venue_identity_keys vk JOIN exclusion_keys ek ON ek.key=vk.key WHERE vk.venue_id=v.id) ORDER BY v.rowid",p==='/api/venues'?'all':'melbourne')]);return json({...JSON.parse(meta?.payload||'{}'),venues:payloads(rows)});
 }
 if(p==='/api/exclusions'){if(req.method!=='GET')return json({error:'Action unavailable.'},405);return json({records:(await query(db,'SELECT * FROM exclusions ORDER BY removed_at DESC')).map(r=>({id:r.id,venue:JSON.parse(r.snapshot),removedAt:r.removed_at}))});}
 const exclusion=p.match(/^\/api\/exclusions\/([^/]+)$/);
 if(exclusion){const id=decodeURIComponent(exclusion[1]);if(req.method==='POST'){const record=await one(db,'SELECT payload FROM venues WHERE id=?',id);if(!record)return json({error:'Venue not found.'},404);const keys=await query(db,'SELECT key FROM venue_identity_keys WHERE venue_id=?',id);await db.batch([db.prepare('INSERT INTO exclusions(id,snapshot,removed_by) VALUES(?,?,?) ON CONFLICT(id) DO NOTHING').bind(id,record.payload,user.id),...keys.map(k=>db.prepare('INSERT INTO exclusion_keys(key,exclusion_id) VALUES(?,?) ON CONFLICT(key) DO NOTHING').bind(k.key,id)),audit(db,user,'venue',id,'Venue excluded')]);return json({ok:true});}if(req.method==='DELETE'){await db.batch([db.prepare('DELETE FROM exclusion_keys WHERE exclusion_id=?').bind(id),db.prepare('DELETE FROM exclusions WHERE id=?').bind(id),audit(db,user,'venue',id,'Venue restored')]);return json({ok:true});}}
 if(p==='/api/customers')return json({records:await query(db,"SELECT DISTINCT c.* FROM companies c JOIN opportunities o ON o.company_id=c.id JOIN milestone_confirmations m ON m.opportunity_id=o.id WHERE m.milestone='V3' AND m.revoked_at IS NULL ORDER BY c.name")});
 if(p==='/api/companies'){return json({records:await query(db,'SELECT c.*,p.type partner_type,p.status partner_status FROM companies c LEFT JOIN partners p ON p.company_id=c.id ORDER BY c.name')});}
 if(p==='/api/opportunities')return json({records:await query(db,`SELECT o.*,c.name company_name,(SELECT max(milestone) FROM milestone_confirmations m WHERE m.opportunity_id=o.id AND revoked_at IS NULL) milestone FROM opportunities o LEFT JOIN companies c ON c.id=o.company_id`)});
 if(p==='/api/files'&&req.method==='GET')return json({records:await query(db,'SELECT * FROM files ORDER BY created_at DESC')});
 if(p==='/api/files'&&req.method==='POST'){
  const length=Number(req.headers.get('content-length'));if(length>10*1024*1024)return json({error:'Choose a file under 10 MB.'},413);const form=await req.formData(),file=form.get('file'),projectId=form.get('project_id')||null;
  if(!file||typeof file.arrayBuffer!=='function'||file.size>10*1024*1024)throw Error('Choose a file under 10 MB.');if(projectId&&!await one(db,'SELECT id FROM work_projects WHERE id=?',projectId))throw Error('Project not found.');
  const id=uid(),key='files/'+id,bytes=await file.arrayBuffer(),hash=await sha(bytes),type=file.type||'application/octet-stream';
  await env.FILES.put(key,bytes,{httpMetadata:{contentType:type},customMetadata:{name:file.name.slice(0,200),sha256:hash}});
  try{await db.batch([db.prepare('INSERT INTO files(id,object_key,name,content_type,bytes,sha256,owner_id,project_id,category) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,key,file.name.slice(0,200),type,file.size,hash,user.id,projectId,String(form.get('category')||'sales_material').slice(0,50)),audit(db,user,projectId?'project':'file',projectId||id,'File uploaded',{name:file.name})]);}catch(e){await env.FILES.delete(key);throw e;}return json({id},201);
 }
 const file=p.match(/^\/api\/files\/([^/]+)$/);
 if(file&&req.method==='GET'){const record=await one(db,'SELECT * FROM files WHERE id=?',file[1]);if(!record)return json({error:'File not found.'},404);const object=await env.FILES.get(record.object_key);if(!object)return json({error:'File temporarily unavailable.'},503);return new Response(object.body,{headers:{'content-type':record.content_type,'content-disposition':`attachment; filename*=UTF-8''${encodeURIComponent(record.name)}`,'cache-control':'private, no-store'}});}
 if(p.startsWith('/api/'))return json({error:'This action is not available.'},404);
 const response=await env.ASSETS.fetch(req);const h=new Headers(response.headers);h.set('cache-control','private, no-store');return new Response(response.body,{status:response.status,headers:h});
}
export default {async fetch(req,env){try{return secure(await fetchHandler(req,env));}catch(e){console.error('Workspace request failed',new URL(req.url).pathname,e.message);const validation=!/SQLITE|D1_|R2_|fetch failed|internal|constraint/i.test(e.message);return secure(json({error:validation?e.message:'Your changes could not be saved. Please retry; your input has been kept.'},validation?400:503));}}};
