import test from 'node:test';
import assert from 'node:assert/strict';
import {eventIdentity,exhibitionTasks,validateProject,safeUrl} from '../worker/model.mjs';
import {identityKeys,isExcluded} from '../worker/venue-identity.mjs';
test('an exhibition identity survives punctuation, case and same-edition date corrections',()=>{assert.equal(eventIdentity({name:'IAAPA Expo – Asia',country:'Singapore',start:'2026-10-02'}),eventIdentity({name:'iaapa expo asia',country:'Singapore',start:'2026-11-03'}));assert.notEqual(eventIdentity({name:'Expo',country:'Singapore',start:'2026-01-01'}),eventIdentity({name:'Expo',country:'Singapore',start:'2027-01-01'}));});
test('all exhibition levels extend the same work template',()=>{for(const title of exhibitionTasks(1))assert.ok(exhibitionTasks(2).includes(title));for(const title of exhibitionTasks(2))assert.ok(exhibitionTasks(3).includes(title));assert.equal(new Set(exhibitionTasks(3)).size,exhibitionTasks(3).length);});
test('excluded locations stay excluded after renamed imports with new ids',()=>{const old={id:'old',name:'Old Play',address:'42 Main Street',placeId:'p-1'};const changed={id:'new',name:'New Play',aliases:['Old Play'],address:'42 Main Street',placeId:'p-1'};assert.ok(isExcluded(changed,new Set(identityKeys(old))));assert.ok(!isExcluded({...changed,address:'57 Other St',placeId:'p-2'},new Set(identityKeys(old))));});
test('unsupported statuses and workstreams cannot become new aliases',()=>{assert.throws(()=>validateProject({name:'Visit show',workstream:'exhibition'}));assert.throws(()=>validateProject({name:'Visit show',workstream:'brand_awareness',status:'incomplete'}));assert.throws(()=>validateProject({name:'Visit show',workstream:'brand_awareness',exhibition_level:4}));assert.ok(validateProject({name:'Visit show',workstream:'brand_awareness',status:'draft',exhibition_level:1}));});
test('evidence links reject executable protocols',()=>{assert.equal(safeUrl('javascript:alert(1)'),null);assert.equal(safeUrl('data:text/html,test'),null);assert.equal(safeUrl('https://example.com/source'),'https://example.com/source');});
